---

- name: install HAProxy & HTTPD
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - httpd
    - httpd-tools
    - haproxy

- name: configure haproxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
