---

- name: install HAProxy
  yum:
    name: "{{ packages }}"
    state: latest
    vars:
      packages:
        - haproxy

- name: enable & start haproxy at boot
  service:
    name: haproxy
    enabled: yes
    state: started

- name: configure haproxy
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
    - restart haproxy
